### ISSUE TITLE
error TS5014: Failed to parse file 'tsconfig.json'

### ISSUE THREAD

**Issue by rjousse18** [MattMoony/figaro#15]
When i run python3 figaro.py -g I have this error :

`
Config file ("/home/remi/Documents/figaro/figaro/gui/dist/config/conf.json") missing ... trying to (re)compile GUI ... 

> figaro-gui@1.0.0 build
> tsc

error TS5014: Failed to parse file 'tsconfig.json': Unexpected token / in JSON at position 71.
npm ERR! code 1
npm ERR! path /home/remi/Documents/figaro/figaro/gui
npm ERR! command failed
npm ERR! command sh -c tsc

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/remi/.npm/_logs/2021-03-28T11_26_45_757Z-debug.log
Config file "/home/remi/Documents/figaro/figaro/gui/dist/config/conf.json" doesn't exist ... 

`

What am I doing wrong ?

**Comment by MattMoony** [comment]
The GUI part is still in development. The simplest way to get access to the GUI right now is using `python3 figaro.py -s` and, in another console, `cd figaro/gui/web && npm run dev` - then view the GUI through a web browser at http://localhost:8000.

I'll turn the GUI into a proper _Electron_ desktop app, when I find the time ... :o Kinda lacking that at the moment ... ^^

**Comment by MattMoony** [comment]
Please, reply if the problem persists

**Comment by rjousse18** [comment]
ok thanks !
