### ISSUE TITLE
Failed setup after following all prescribed steps

### ISSUE THREAD

**Issue by OliverGronowski** [MattMoony/figaro#16]
**Describe the bug**
I was installing the program but I got this error (See screenshot).

**To Reproduce**
Steps to reproduce the behaviour:
1. Download `master` branch as a ZIP
2. Unzip
3. Open Powershell in administrator mode
4. Execute and confirm this command: `Set-ExecutionPolicy RemoteSigned`
4. Type `cd <location of unzipped folder>`
5. Executing and confirming everything of the command `.\setup.ps1`
6. Execute `python figaro.py`

**Expected behaviour**
To have a succesful setup

**Screenshots**
![Bug_Figaro](https://user-images.githubusercontent.com/45373843/113872944-a4d10000-97b4-11eb-8074-0d8106fa21c5.jpg)

**Desktop:**
 - OS: Windows 10
 - Version 3

**Additional context**
Python 3.9, npm and pip were already on my machine

**Comment by MattMoony** [comment]
Seems like I need to fix some path issues in the setup script...

For now, just running the setup script from the install directory should work though.

Feel free to reply if it doesn't 👍
