### ISSUE TITLE
Config file doesn't exist

### ISSUE THREAD

**Issue by pscll** [MattMoony/figaro#18]
Latest build as of today
Windows 10

after running setup.ps1 this happens

![image](https://user-images.githubusercontent.com/26367116/119037419-3e91ec80-b9b2-11eb-84dd-65c202ad1a02.png)

**Comment by MattMoony** [comment]
Hi,

just for clarification purposes: Does this happen when you run `setup.ps1` or after `setup.ps1` has finished and you run the python script?

**Comment by MattMoony** [comment]
As it turns out, I did forget to include one `npm i` in my previous setup scripts... This should have been fixed by c0551f65a9bea2aa8880c1af6307105b17b1d006, however... Feel free to reopen this if it wasn't!
