### ISSUE TITLE
" node : The term 'node' is not recognized  "

### ISSUE THREAD

**Issue by zeppelin-vences** [MattMoony/figaro#19]
Hi all,
Any idea how could i fix this error? 

I first _Set-ExecutionPolicy RemoteSigned_ as per instructions. Then changed to _Set-ExecutionPolicy Unrestricted_  and  _.\setup.ps1_    seemed to run but then stopped showing the following error.   

Many thanks

![Figaro](https://user-images.githubusercontent.com/30063787/119274664-5940ad00-bbce-11eb-8014-314f5c3dadbe.png)

**Comment by MattMoony** [comment]
Hi,

this is probably because you either don't have `node` in your path or not installed at all. In case you really don't have it, you can just download and install it from [here](https://nodejs.org/en/).

Hope this fixes your problem!
