### ISSUE TITLE
Install Issues w/Pash

### ISSUE THREAD

**Issue by mm12** [MattMoony/figaro#20]
Failed to automatically install Pash on run. Ran requirements install, still failed. Manually installed with pip3, installed node, updated Pip, now when gui is run it outputs that on line 3 (where pash is imported) `ImportError: No module named pash.misc`
Confirmed misc.py exists in Pash

OS: MacOS 10.14.6
Python version: Python 3.9.2

**Comment by MattMoony** [comment]
@mm12, sounds interesting... ^^ Did you get any more output that might help while troubleshooting? :P

**Comment by mm12** [comment]
Run gui.sh:
```
USER-Macbook-Pro:figaro USERNAME$ /Users/USERNAME/Documents/GitHub/figaro/gui.sh 

> figaro-gui@1.0.0 dev:nodemon /Users/USERNAME/Documents/GitHub/figaro/figaro/gui
> npm run build && electron .


> figaro-gui@1.0.0 build /Users/USERNAME/Documents/GitHub/figaro/figaro/gui
> tsc

Traceback (most recent call last):
  File "/Users/USERNAME/Documents/GitHub/figaro/figaro.py", line 3, in <module>
    import pash.misc, pash.cmds, sys

ImportError: No module named pash.misc
```
if I run `python3 figaro.py` it starts a terminal app.

**Comment by MattMoony** [comment]
And u said running `python3 -m pip install pash-cmd` fails, right? Does that generate more error-output?

**Comment by mm12** [comment]
No, it doesn't fail, but running the setup or using requirements.txt fails. I installed using `pip3 install pash-cmd`. 
I think the setup failed because I didn't have node installed when I was installing everything. I reran it and it said "found 563 vulnerabilities (62 moderate, 499 high, 2 critical)". and requirements.txt worked fine too now. 

But it still says it cant fine  pash.misc

**Comment by MattMoony** [comment]
This sounds a lot like #14, but at least there was some sort of error output there... ^^
You said that the terminal app starts, when you run `python3 figaro.py`, right? You don't get any traceback there either...?

**Comment by mm12** [comment]
right, `python3 figaro.py` opens the term app: 
![image](https://user-images.githubusercontent.com/5874051/120120913-4f86ee80-c166-11eb-827e-d614d334f532.png)

**Comment by mm12** [comment]
Unsure if this is related, but this happens now:
![image](https://user-images.githubusercontent.com/5874051/120251817-538b3d00-c248-11eb-9426-df89b7a0d68c.png)

**Comment by mm12** [comment]
> Unsure if this is related, but this happens now:
> ![image](https://user-images.githubusercontent.com/5874051/120251817-538b3d00-c248-11eb-9426-df89b7a0d68c.png)

Nevermind, Issue #21
