### ISSUE TITLE
Set up fail in M1 Mac Big Sur

### ISSUE THREAD

**Issue by Ppang0405** [MattMoony/figaro#25]
**Log**
➜  figaro git:(master) ✗ sh ./setup-mac.sh 
-e [2021-06-12~20:54|+] Setting up "Figaro"
-e [2021-06-12~20:54|*] Checking requirements ... 
-e [2021-06-12~20:54|*] Checking python/pip installation ... 
-e [2021-06-12~20:54|+] Functioning python3 setup detected!
-e [2021-06-12~20:54|+] Functioning pip3 setup detected!
-e [2021-06-12~20:54|*] Checking node/npm installation ... 
-e [2021-06-12~20:54|+] Functional node installation found!
-e [2021-06-12~20:54|+] Functioning npm setup found!
-e [2021-06-12~20:54|*] Installing python requirements ... 
Collecting argon2-cffi==20.1.0
  Downloading argon2-cffi-20.1.0.tar.gz (1.8 MB)
     |████████████████████████████████| 1.8 MB 1.1 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/homebrew/opt/python@3.9/bin/python3.9 /opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/jm/3n3gn6057jxgd0cjr_vwz_mh0000gn/T/tmp23_xy1nl
         cwd: /private/var/folders/jm/3n3gn6057jxgd0cjr_vwz_mh0000gn/T/pip-install-1yufu3gu/argon2-cffi_731ea7430e204c39b5aa0461664974a3
    Complete output (38 lines):
    Traceback (most recent call last):
      File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
        main()
      File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 365, in <module>
        setup(
      File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 434, in __init__
        _Distribution.__init__(self, {
      File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 743, in finalize_options
        ep(self)
      File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 750, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/private/var/folders/jm/3n3gn6057jxgd0cjr_vwz_mh0000gn/T/pip-build-env-bzktk4ug/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/private/var/folders/jm/3n3gn6057jxgd0cjr_vwz_mh0000gn/T/pip-build-env-bzktk4ug/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/private/var/folders/jm/3n3gn6057jxgd0cjr_vwz_mh0000gn/T/pip-build-env-bzktk4ug/overlay/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/argon2/_ffi_build.py", line 28, in <module>
        ffi = FFI()
      File "/private/var/folders/jm/3n3gn6057jxgd0cjr_vwz_mh0000gn/T/pip-build-env-bzktk4ug/overlay/lib/python3.9/site-packages/cffi/api.py", line 48, in __init__
        import _cffi_backend as backend
    ImportError: dlopen(/private/var/folders/jm/3n3gn6057jxgd0cjr_vwz_mh0000gn/T/pip-build-env-bzktk4ug/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): Library not loaded: @rpath/libffi.7.dylib
      Referenced from: /private/var/folders/jm/3n3gn6057jxgd0cjr_vwz_mh0000gn/T/pip-build-env-bzktk4ug/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
      Reason: image not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/74/fd/d78e003a79c453e8454197092fce9d1c6099445b7e7da0b04eb4fe1dbab7/argon2-cffi-20.1.0.tar.gz#sha256=d8029b2d3e4b4cea770e9e5a0104dd8fa185c1724a0f01528ae4826a6d25f97d (from https://pypi.org/simple/argon2-cffi/). Command errored out with exit status 1: /opt/homebrew/opt/python@3.9/bin/python3.9 /opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/jm/3n3gn6057jxgd0cjr_vwz_mh0000gn/T/tmp23_xy1nl Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement argon2-cffi==20.1.0 (from versions: 15.0.0b5, 15.0.0, 15.0.1, 16.0.0, 16.1.0, 16.2.0, 16.3.0, 18.1.0, 18.2.0, 18.3.0, 19.1.0, 19.2.0, 20.1.0)
ERROR: No matching distribution found for argon2-cffi==20.1.0
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/opt/homebrew/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.
-e [2021-06-12~20:54|*] Installing node requirements (electron part) ... 
npm ERR! code 1
npm ERR! path /Users/truongnguyen/Documents/coding_stuff/tool/figaro/figaro/gui/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.4.4/electron-v9.4.4-darwin-arm64.zip
npm ERR!     at EventEmitter.<anonymous> (/Users/truongnguyen/Documents/coding_stuff/tool/figaro/figaro/gui/node_modules/got/source/as-stream.js:35:24)
npm ERR!     at EventEmitter.emit (node:events:365:28)
npm ERR!     at module.exports (/Users/truongnguyen/Documents/coding_stuff/tool/figaro/figaro/gui/node_modules/got/source/get-response.js:22:10)
npm ERR!     at ClientRequest.handleResponse (/Users/truongnguyen/Documents/coding_stuff/tool/figaro/figaro/gui/node_modules/got/source/request-as-event-emitter.js:155:5)
npm ERR!     at Object.onceWrapper (node:events:472:26)
npm ERR!     at ClientRequest.emit (node:events:377:35)
npm ERR!     at ClientRequest.origin.emit (/Users/truongnguyen/Documents/coding_stuff/tool/figaro/figaro/gui/node_modules/@szmarczak/http-timer/source/index.js:37:11)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:621:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:127:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:487:22)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/truongnguyen/.npm/_logs/2021-06-12T13_54_36_302Z-debug.log
-e [2021-06-12~20:54|*] Installing node requirements (web/gatsby part) ... 
npm ERR! code 1
npm ERR! path /Users/truongnguyen/Documents/coding_stuff/tool/figaro/figaro/gui/web/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
npm ERR! info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-darwin-arm64v8.tar.br
npm ERR! ERR! sharp Prebuilt libvips 8.10.5 binaries are not yet available for darwin-arm64v8
npm ERR! info sharp Attempting to build from source via node-gyp but this may fail due to the above error
npm ERR! info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.2.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.5 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
npm ERR! (node:4485) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/truongnguyen/Documents/coding_stuff/tool/figaro/figaro/gui/web/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/truongnguyen/Documents/coding_stuff/tool/figaro/figaro/gui/web/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/truongnguyen/Documents/coding_stuff/tool/figaro/figaro/gui/web/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/truongnguyen/Library/Caches/node-gyp/16.2.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/truongnguyen/Library/Caches/node-gyp/16.2.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/truongnguyen/Documents/coding_stuff/tool/figaro/figaro/gui/web/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/truongnguyen/Library/Caches/node-gyp/16.2.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/truongnguyen/Documents/coding_stuff/tool/figaro/figaro/gui/web/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
npm ERR! ../src/common.cc:24:10: fatal error: 'vips/vips8' file not found
npm ERR! #include <vips/vips8>
npm ERR!          ^~~~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/sharp/src/common.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/truongnguyen/Documents/coding_stuff/tool/figaro/figaro/gui/web/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.5.0
npm ERR! gyp ERR! command "/Users/truongnguyen/.asdf/installs/nodejs/16.2.0/bin/node" "/Users/truongnguyen/Documents/coding_stuff/tool/figaro/figaro/gui/web/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/truongnguyen/Documents/coding_stuff/tool/figaro/figaro/gui/web/node_modules/sharp
npm ERR! gyp ERR! node -v v16.2.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

**Comment by Ppang0405** [comment]
Any help? pls

**Comment by ghost** [comment]
I’m having the same problem. Could some please help?

or at least some thing simila
