### ISSUE TITLE
Filenames with Spaces do not work in the GUI

### ISSUE THREAD

**Issue by 0Adiber** [MattMoony/figaro#8]
**Describe the bug**
When I put a File with spaces in the `/res/sounds` directory, I can play them using the command line (by adding quotes around them), but in the GUI it won't play.. :(
e.g. "Microsoft Windows XP Startup Sound"

**To Reproduce**
Steps to reproduce the behaviour:
1. Put a file with spaces in the `res/sounds` directory
2. Try to play the sound via the GUI

**Expected behaviour**
The sound plays.

**Screenshots**
![image](https://user-images.githubusercontent.com/44465736/104204780-ee1be880-542d-11eb-8255-480e3045695e.png)
![image](https://user-images.githubusercontent.com/44465736/104204880-07bd3000-542e-11eb-8b22-5f2194968e55.png)
... the Sound does not play...

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 10.0.19041 Build 19041

**Comment by MattMoony** [comment]
Thank you for your contribution! 👍 😄
